"""init_tables

Revision ID: 7b834378524f
Revises: 
Create Date: 2026-08-06 17:05:22.806446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b834378524f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('main_profession', sa.String(length=16), nullable=False),
    sa.Column('sub_profession', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_guild_id'), 'members', ['guild_id'], unique=False)
    op.create_index(op.f('ix_members_main_profession'), 'members', ['main_profession'], unique=False)
    op.create_index(op.f('ix_members_name'), 'members', ['name'], unique=False)
    op.create_index(op.f('ix_members_status'), 'members', ['status'], unique=False)
    op.create_table('profession_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('profession', sa.String(length=16), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'profession', name='uq_profession_guild')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('opponent', sa.String(length=64), nullable=False),
    sa.Column('match_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('round_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rounds BETWEEN 1 AND 3', name='ck_schedule_rounds'),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_guild_id'), 'schedules', ['guild_id'], unique=False)
    op.create_index(op.f('ix_schedules_match_time'), 'schedules', ['match_time'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('plain_password', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_guild_id'), 'users', ['guild_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('member_name', sa.String(length=32), nullable=False),
    sa.Column('profession', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'member_id', name='uq_attendance_schedule_member')
    )
    op.create_index(op.f('ix_attendance_records_member_id'), 'attendance_records', ['member_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_schedule_id'), 'attendance_records', ['schedule_id'], unique=False)
    op.create_table('lineups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id')
    )
    op.create_table('match_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=32), nullable=False),
    sa.Column('profession', sa.String(length=16), nullable=True),
    sa.Column('camp', sa.String(length=32), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('springs', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('resource', sa.Integer(), nullable=False),
    sa.Column('player_damage', sa.Integer(), nullable=False),
    sa.Column('armor_break_damage', sa.Integer(), nullable=False),
    sa.Column('building_damage', sa.Integer(), nullable=False),
    sa.Column('tower_break_damage', sa.Integer(), nullable=False),
    sa.Column('healing', sa.Integer(), nullable=False),
    sa.Column('damage_taken', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('revives', sa.Integer(), nullable=False),
    sa.Column('fen_gu', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_data_schedule_id'), 'match_data', ['schedule_id'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('member_name', sa.String(length=32), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('review_remark', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'member_id', 'round_number', name='uq_recording_schedule_member_round')
    )
    op.create_index(op.f('ix_recordings_member_id'), 'recordings', ['member_id'], unique=False)
    op.create_index(op.f('ix_recordings_schedule_id'), 'recordings', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_recordings_status'), 'recordings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recordings_status'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_schedule_id'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_member_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_match_data_schedule_id'), table_name='match_data')
    op.drop_table('match_data')
    op.drop_table('lineups')
    op.drop_index(op.f('ix_attendance_records_schedule_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_member_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_users_guild_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_schedules_match_time'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_guild_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_table('profession_configs')
    op.drop_index(op.f('ix_members_status'), table_name='members')
    op.drop_index(op.f('ix_members_name'), table_name='members')
    op.drop_index(op.f('ix_members_main_profession'), table_name='members')
    op.drop_index(op.f('ix_members_guild_id'), table_name='members')
    op.drop_table('members')
    op.drop_table('guilds')
    # ### end Alembic commands ###
