""""add_lineup_remarks"

Revision ID: dbb752d924fe
Revises: a1b2c3d4e5f6
Create Date: 2026-08-18 16:26:54.069884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbb752d924fe'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lineups', sa.Column('title_remark', sa.String(length=255), nullable=True))
    op.add_column('lineups', sa.Column('groups_remark', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lineups', 'groups_remark')
    op.drop_column('lineups', 'title_remark')
    # ### end Alembic commands ###
